plugins { id 'com.android.application' }

def bootstrapToken = (System.getenv("NODE_BOOTSTRAP_TOKEN") ?: "").toString()

android {
    namespace 'id.domainradar.node'
    buildFeatures { buildConfig true }
    compileSdk 35

    defaultConfig {
        applicationId 'com.pentagon.providernode'
        minSdk 26
        targetSdk 35
        versionCode 171
        versionName '1.7.1'
        buildConfigField "String", "BOOTSTRAP_TOKEN", "\"${bootstrapToken}\""
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
